Vagrant.configure("2") do |config|
	config.vm.box = "schooldaily64"
	config.vm.box_url = "file://schooldaily64.box"
	config.vm.host_name = "postgresql"
	config.vm.provision :shell, path: "provision.sh"
	config.vm.network :forwarded_port, guest:5432, host:15432
	config.vm.network :forwarded_port, guest:5433, host:15433
	config.vm.network "public_network", ip: "192.168.0.15"
end
