Vagrant.configure("2") do |config|
	config.vm.box = "ci-server.box"
	config.vm.box_url = "file://ci-server.box"
	config.vm.host_name = "jenkins"
  config.vm.synced_folder "shareddir/", "/home/vagrant"
	config.vm.provision :shell, path: "provision.sh"
	config.vm.network :forwarded_port, guest:6060, host:6060  
  	config.vm.network :forwarded_port, guest:5432, host:25432
  	config.vm.network :forwarded_port, guest:9000, host:9000
  	config.vm.network :forwarded_port, guest:8440, host:8440
    config.vm.network :forwarded_port, guest:8449, host:8449
  	config.vm.network "public_network", ip: "192.168.0.17"
  	
  	config.vm.provider "virtualbox" do |vb|
    	vb.customize ["modifyvm", :id, "--memory", "2560"]
  	end  
end
