ALTER TABLE users ADD email VARCHAR(80) NULL;
ALTER TABLE users ADD firstname VARCHAR(50) NULL;
ALTER TABLE users ADD lastname VARCHAR(50) NULL;
ALTER TABLE users ADD facebook_id VARCHAR(500) NULL;
ALTER TABLE users ADD facebook_image VARCHAR(500) NULL;
